name: Upload Shorts

on:
  schedule:
    # 10:00 AM IST (04:30 UTC)
    - cron: "30 4 * * *"

    # 10:00 PM IST (16:30 UTC)
    - cron: "30 16 * * *"

  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run uploader
        run: python upload.py
        env:
          FOLDER_ID: ${{ secrets.FOLDER_ID }}
          UPLOADED_FOLDER_ID: ${{ secrets.UPLOADED_FOLDER_ID }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}

      - name: Commit updated episode number
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add episode.txt
          git commit -m "Update episode number" || echo "No changes to commit"
          git push
